image:
  file: .gitpod.dockerfile

tasks:
    - before: nvm install 16.14.2 && nvm use 16.14.2
      init: npm install
      command: npm run start-server

ports:
    - port: 8080
      onOpen: open-preview
