image:
  file: .gitpod.dockerfile

tasks:
    - before: nvm install 16.19.0 && nvm use 16.19.0
      init: npm install
      command: npm run start-server

ports:
    - port: 8080
      onOpen: open-preview
