image:
  file: .gitpod.dockerfile

tasks:
    - before: nvm install 16.13.1 && nvm use 16.13.1
      init: npm install
      command: npm run start-server

ports:
    - port: 8080
      onOpen: open-preview
