module.exports = [
    // label names
    { type: 'label', name: 'inbox' },
    { type: 'label', name: 'disableVersioning' },
    { type: 'label', name: 'calendarRoot' },
    { type: 'label', name: 'archived' },
    { type: 'label', name: 'excludeFromExport' },
    { type: 'label', name: 'disableInclusion' },
    { type: 'label', name: 'appCss' },
    { type: 'label', name: 'appTheme' },
    { type: 'label', name: 'hidePromotedAttributes' },
    { type: 'label', name: 'readOnly' },
    { type: 'label', name: 'autoReadOnlyDisabled' },
    { type: 'label', name: 'hoistedCssClass' },
    { type: 'label', name: 'cssClass' },
    { type: 'label', name: 'iconClass' },
    { type: 'label', name: 'keyboardShortcut' },
    { type: 'label', name: 'run', isDangerous: true },
    { type: 'label', name: 'runOnInstance', isDangerous: false },
    { type: 'label', name: 'runAtHour', isDangerous: false },
    { type: 'label', name: 'customRequestHandler', isDangerous: true },
    { type: 'label', name: 'customResourceProvider', isDangerous: true },
    { type: 'label', name: 'widget', isDangerous: true },
    { type: 'label', name: 'noteInfoWidgetDisabled' },
    { type: 'label', name: 'linkMapWidgetDisabled' },
    { type: 'label', name: 'noteRevisionsWidgetDisabled' },
    { type: 'label', name: 'whatLinksHereWidgetDisabled' },
    { type: 'label', name: 'similarNotesWidgetDisabled' },
    { type: 'label', name: 'workspace' },
    { type: 'label', name: 'workspaceIconClass' },
    { type: 'label', name: 'workspaceTabBackgroundColor' },
    { type: 'label', name: 'searchHome' },
    { type: 'label', name: 'hoistedInbox' },
    { type: 'label', name: 'hoistedSearchHome' },
    { type: 'label', name: 'sqlConsoleHome' },
    { type: 'label', name: 'datePattern' },
    { type: 'label', name: 'pageSize' },
    { type: 'label', name: 'viewType' },
    { type: 'label', name: 'mapRootNoteId' },
    { type: 'label', name: 'bookmarked' },
    { type: 'label', name: 'bookmarkFolder' },
    { type: 'label', name: 'sorted' },
    { type: 'label', name: 'top' },
    { type: 'label', name: 'fullContentWidth' },
    { type: 'label', name: 'shareHiddenFromTree' },
    { type: 'label', name: 'shareAlias' },
    { type: 'label', name: 'shareOmitDefaultCss' },
    { type: 'label', name: 'shareRoot' },

    // relation names
    { type: 'relation', name: 'internalLink' },
    { type: 'relation', name: 'imageLink' },
    { type: 'relation', name: 'relationMapLink' },
    { type: 'relation', name: 'includeMapLink' },
    { type: 'relation', name: 'runOnNoteCreation', isDangerous: true },
    { type: 'relation', name: 'runOnNoteTitleChange', isDangerous: true },
    { type: 'relation', name: 'runOnNoteChange', isDangerous: true },
    { type: 'relation', name: 'runOnChildNoteCreation', isDangerous: true },
    { type: 'relation', name: 'runOnAttributeCreation', isDangerous: true },
    { type: 'relation', name: 'runOnAttributeChange', isDangerous: true },
    { type: 'relation', name: 'template' },
    { type: 'relation', name: 'widget', isDangerous: true },
    { type: 'relation', name: 'renderNote', isDangerous: true },
    { type: 'relation', name: 'shareCss' },
    { type: 'relation', name: 'shareJs' },
    { type: 'relation', name: 'shareFavicon' },
];
