name: Bug Report
description: Report a bug
title: "(Bug report) "
labels: "Type: Bug"
body:
- type: input
  attributes:
    label: Trilium Version
    description: What version of Trilium are you using?
    placeholder: 0.57.0-beta
  validations:
    required: true
- type: dropdown
  attributes:
    label: What operating system are you using?
    options:
      - Windows
      - macOS
      - Ubuntu
      - Other Linux
      - Other (specify below)
  validations:
    required: true
- type: dropdown
  attributes:
    label: What is your setup?
    description: https://github.com/zadam/trilium/wiki#choose-the-setup
    options:
      - Local (no sync)
      - Local + server sync
      - Server access only
  validations:
    required: true
- type: input
  attributes:
    label: Operating System Version
    description: What operating system version are you using? On Windows, click Start button > Settings > System > About. On macOS, click the Apple Menu > About This Mac. On Linux, use lsb_release or uname -a.
    placeholder: "e.g. Windows 10 version 1909, macOS Catalina 10.15.7, or Ubuntu 20.04"
  validations:
    required: true
- type: textarea
  attributes:
    label: Description
    description: A clear and concise description of the bug and any additional information.
  validations:
    required: true
- type: textarea
  attributes:
    label: Error logs
    description: Please provide error logs, see [wiki page](https://github.com/zadam/trilium/wiki/Error-logs) for instructions on how to submit them.
  validations:
    required: false
