POST {{triliumHost}}/etapi/create-note
Authorization: {{authToken}}
Content-Type: application/json

{
  "parentNoteId": "root",
  "title": "Hello",
  "type": "image",
  "mime": "image/png",
  "content": ""
}

> {% client.global.set("createdNoteId", response.body.note.noteId); %}

###

PUT {{triliumHost}}/etapi/notes/{{createdNoteId}}/content
Authorization: {{authToken}}
Content-Type: application/octet-stream
Content-Transfer-Encoding: binary

< ../images/icon-color.png

> {% client.assert(response.status === 204); %}

