POST {{triliumHost}}/etapi/create-note
Authorization: {{authToken}}
Content-Type: application/json

{
  "parentNoteId": "root",
  "title": "Hello",
  "type": "text",
  "content": "Hi there!"
}

> {% client.global.set("createdNoteId", response.body.note.noteId); %}

###

POST {{triliumHost}}/etapi/attachments
Authorization: {{authToken}}
Content-Type: application/json

{
  "ownerId": "{{createdNoteId}}",
  "role": "file",
  "mime": "text/plain",
  "title": "my attachment",
  "content": "text"
}

> {% client.global.set("createdAttachmentId", response.body.attachmentId); %}

###

DELETE {{triliumHost}}/etapi/attachments/{{createdAttachmentId}}
Authorization: {{authToken}}

> {% client.assert(response.status === 204, "Response status is not 204"); %}

### repeat the DELETE request to test the idempotency

DELETE {{triliumHost}}/etapi/attachments/{{createdAttachmentId}}
Authorization: {{authToken}}

> {% client.assert(response.status === 204, "Response status is not 204"); %}

###

GET {{triliumHost}}/etapi/attachments/{{createdAttachmentId}}
Authorization: {{authToken}}

> {%
    client.assert(response.status === 404, "Response status is not 404");
    client.assert(response.body.code === "ATTACHMENT_NOT_FOUND");
%}
