module.exports = {
    UPDATE_CONTENT: 'CONTENT',
    UPDATE_TITLE: 'TITLE',
    CHANGE_POSITION: 'POSITION',
    CREATE_NOTE: 'CREATE',
    DELETE_NOTE: 'DELETE',
    CHANGE_PARENT: 'PARENT',
    ENCRYPTION: 'ENCRYPTION',
    CHANGE_PASSWORD: 'PASSWORD',
    SETTINGS: 'SETTINGS'
};